#!/bin/bash
# MySQL 初回起動時のみ実行（/docker-entrypoint-initdb.d）
# root で flyway / app 専用ユーザーを作成し、最小権限を付与する
set -euo pipefail

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE USER IF NOT EXISTS '${MYSQL_FLYWAY_USER}'@'%' IDENTIFIED BY '${MYSQL_FLYWAY_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, REFERENCES
  ON \`${MYSQL_DATABASE}\`.*
  TO '${MYSQL_FLYWAY_USER}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE
  ON \`${MYSQL_DATABASE}\`.*
  TO '${MYSQL_APP_USER}'@'%';

FLUSH PRIVILEGES;
EOSQL
